### Variables

@apiUrl = http://localhost:3000

### Health
GET {{apiUrl}}/health HTTP/1.1
### POST USER
POST {{apiUrl}}/users HTTP/1.1
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com"
}
###
POST {{apiUrl}}/posts HTTP/1.1
Content-Type: application/json

{
  "description": "teste",
  "title": "teste",
  "userId": 1
}